spring:
  application:
    name: scalable-cache-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scalable_cache_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Admin@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  security:
    jwt:
      secret: ${JWT_SECRET:this-is-a-very-long-local-development-secret-key}
      expiration-ms: ${JWT_EXPIRATION_MS:900000} #15 minutes

  refresh-token:
    expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS:604800000} #7 days

  admin:
    email: ${ADMIN_EMAIL:admin@test.com}
    password: ${ADMIN_PASSWORD:password123}


