apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: scalable_cache_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: this-is-a-very-long-kubernetes-development-secret-key